package com.thejoa703.dao;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Mapper;

import com.thejoa703.dto.Recipes3Dto;
import com.thejoa703.dto.RecipesIngre3;
import com.thejoa703.dto.RecipesStep3;

@Mapper
public interface Recipes3Dao {
    // recipes3
    public int insertRecipe(Recipes3Dto recipe);
    public int updateRecipe(Recipes3Dto recipe);
    public int deleteRecipe(int recipeId);
    public Recipes3Dto selectRecipeById(int recipeId);
    public List<Recipes3Dto> selectRecipeAllPaged(Map<String, Object> params); // rStart, rEnd, category
    public int countSearchRecipes(Map<String, Object> params);
    public List<Recipes3Dto> searchRecipesPaged(Map<String, Object> params); // rStart, rEnd, keyword, searchField, sort, category
    public int incrementViews(int recipeId);

    // recipes_ingre3
    public int insertIngre(RecipesIngre3 ingre);
    public int deleteIngreByRecipeId(int recipeId);
    public List<RecipesIngre3> selectIngreByRecipeId(int recipeId);

    // recipes_step3
    public int insertStep(RecipesStep3 step);
    public int deleteStepByRecipeId(int recipeId);
    public List<RecipesStep3> selectStepByRecipeId(int recipeId);

    // likes
    public int insertLike(Map<String, Object> params); // appUserId, recipeId
    public int deleteLike(Map<String, Object> params);
    public int countLikesByRecipe(int recipeId);
    public int existsLike(Map<String, Object> params);

    // search history
    public int insertSearchHistory(Map<String, Object> params); // appUserId, keyword
    public List<Map<String, Object>> topKeywords(int limit);

    // bad words
    List<String> containsBadWords(String text);
    int existsBadWord(String word);
    int insertBadWord(Map<String, Object> params); // wordId generated by selectKey in XML
    int updateBadWord(Map<String, Object> params); // wordId, newWord
    int deleteBadWordById(int wordId);
    int deleteBadWordByWord(String word);
    public List<Map<String, Object>> selectAllBadWords();

    // ai usage
    public int insertAiUsage(Map<String, Object> params); // aiHistId generated by selectKey in XML
    public List<Map<String, Object>> selectAllAiUsage();
    public List<Map<String, Object>> selectAiUsageByUser(int appUserId);
    public int deleteAiUsageById(int aiHistId);
    public int deleteAiUsageByUser(int appUserId);

    // category
    public List<Map<String, Object>> selectAllCategories();
    public String selectCategoryName(int category);
}
